"""Incremental CKL update: merge new scan results into an existing CKL file.

Preserves assessor-entered notes, manual overrides, and Not_Applicable status
while updating stigcode-generated content with the latest scan evidence.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import defusedxml.ElementTree as dET

from stigcode.ingest.xccdf import StigBenchmark
from stigcode.mapping.status import CklStatus, StatusReport

from .ckl import (
    _VULN_ATTRIBUTES,
    AssetInfo,
    _add_stig_data,
    _build_asset,
    _build_stig_info,
    _format_comments,
    _format_finding_details,
    _format_stig_ref,
    _sub_text,
)

# Prefix that stigcode stamps on all auto-generated COMMENTS.
_STIGCODE_COMMENTS_PREFIX = "Stigcode assessment"


@dataclass
class CklConflict:
    """A conflict between an existing CKL status and new scan results."""

    stig_id: str
    existing_status: str
    new_status: str
    existing_comments: str
    reason: str


@dataclass
class UpdateResult:
    """Result of an incremental CKL update."""

    updated_count: int
    preserved_count: int
    conflicts: list[CklConflict]
    total_findings: int


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def parse_existing_ckl(path: Path) -> dict[str, dict]:
    """Parse an existing CKL and return per-finding data keyed by Vuln_Num.

    Uses defusedxml to guard against malicious XML in untrusted CKL files.

    Each value dict has:
        status, finding_details, comments, severity_override,
        severity_justification
    """
    tree = dET.parse(str(path))
    root = tree.getroot()

    findings: dict[str, dict] = {}
    for vuln in root.findall(".//VULN"):
        vuln_num = _get_stig_attr(vuln, "Vuln_Num")
        if not vuln_num:
            continue
        findings[vuln_num] = {
            "status": vuln.findtext("STATUS") or "",
            "finding_details": vuln.findtext("FINDING_DETAILS") or "",
            "comments": vuln.findtext("COMMENTS") or "",
            "severity_override": vuln.findtext("SEVERITY_OVERRIDE") or "",
            "severity_justification": vuln.findtext("SEVERITY_JUSTIFICATION") or "",
        }
    return findings


# ---------------------------------------------------------------------------
# Merge logic helpers
# ---------------------------------------------------------------------------

def _is_assessor_comments(comments: str) -> bool:
    """Return True when the comments field contains assessor-entered content.

    Stigcode-generated comments always start with the prefix constant.
    Anything else is treated as assessor-entered and preserved.
    """
    stripped = comments.strip()
    return bool(stripped) and not stripped.startswith(_STIGCODE_COMMENTS_PREFIX)


def _merge_comments(existing: str, new_stigcode: str) -> str:
    """Merge stigcode-generated comments into the existing comments field.

    If the existing content is assessor-entered it is kept verbatim, with the
    new stigcode assessment appended on a new line.  If the existing content
    was previously generated by stigcode it is replaced in full.
    """
    existing_stripped = existing.strip()

    if not existing_stripped:
        return new_stigcode

    if _is_assessor_comments(existing_stripped):
        # Keep assessor notes; append the updated stigcode assessment.
        return f"{existing_stripped}\n{new_stigcode}"

    # Previous stigcode content — replace it outright.
    return new_stigcode


def _merge_finding_details(existing: str, new_details: str) -> str:
    """Merge finding details, preserving any non-stigcode content.

    Stigcode-generated FINDING_DETAILS start with the review_notes text from
    FindingDetermination (e.g. 'Scanner reported…', 'Automated scan…',
    'Finding inferred via…', 'No CWE mapping…', 'This finding requires…').
    There is no single constant prefix, so we detect assessor content by
    looking for the absence of any known stigcode opener.
    """
    existing_stripped = existing.strip()
    if not existing_stripped:
        return new_details

    # If the existing text is exactly what stigcode would have put there
    # (starts with a recognised scanner/assessment phrase) we can replace it.
    stigcode_openers = (
        "Scanner reported",
        "Automated scan",
        "Finding inferred",
        "No CWE mapping",
        "This finding requires",
    )
    if any(existing_stripped.startswith(p) for p in stigcode_openers):
        return new_details

    # Assessor-entered — preserve it; append new details.
    if new_details:
        return f"{existing_stripped}\n{new_details}"
    return existing_stripped


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def update_ckl(
    existing_ckl_path: Path,
    report: StatusReport,
    benchmark: StigBenchmark,
    output_path: Path,
    asset: AssetInfo | None = None,
    classification: str = "UNCLASSIFIED",
) -> UpdateResult:
    """Merge new scan results into an existing CKL file.

    The existing CKL provides per-finding data that may contain assessor notes
    and manual status overrides.  This function applies the merge rules
    described in the module docstring and writes the result to output_path.

    Returns an UpdateResult summarising what changed.
    """
    if asset is None:
        asset = AssetInfo()

    existing = parse_existing_ckl(existing_ckl_path)

    det_by_id = {d.stig_id: d for d in report.determinations}
    today = date.today().isoformat()
    timestamp_note = f"Updated by stigcode on {today}"

    updated_count = 0
    preserved_count = 0
    conflicts: list[CklConflict] = []

    root = ET.Element("CHECKLIST")
    _build_asset(root, asset)

    stigs = ET.SubElement(root, "STIGS")
    istig = ET.SubElement(stigs, "iSTIG")
    _build_stig_info(istig, benchmark, classification)

    stig_ref = _format_stig_ref(benchmark)

    for finding in benchmark.findings:
        vid = finding.vuln_id
        det = det_by_id.get(vid)
        ex = existing.get(vid, {})

        ex_status = ex.get("status", "")
        ex_comments = ex.get("comments", "")
        ex_details = ex.get("finding_details", "")
        ex_sev_override = ex.get("severity_override", "")
        ex_sev_just = ex.get("severity_justification", "")

        new_status_enum = det.status if det else CklStatus.NOT_REVIEWED
        new_status_str = new_status_enum.value

        # Build new stigcode content strings for this finding.
        new_details = _format_finding_details(det) if det else ""
        new_comments_base = _format_comments(det) if det else ""

        # --- Rule 5: Never override Not_Applicable ---
        if ex_status == CklStatus.NOT_APPLICABLE.value:
            preserved_count += 1
            final_status = ex_status
            final_details = ex_details
            final_comments = ex_comments
        # --- Rule 3: NotAFinding → Open is a conflict ---
        elif (
            ex_status == CklStatus.NOT_A_FINDING.value
            and new_status_str == CklStatus.OPEN.value
            and _is_assessor_comments(ex_comments)
        ):
            conflicts.append(CklConflict(
                stig_id=vid,
                existing_status=ex_status,
                new_status=new_status_str,
                existing_comments=ex_comments,
                reason=(
                    "Assessor marked NotAFinding but new scan reports Open. "
                    "Manual review required."
                ),
            ))
            # Keep assessor's status but surface the new evidence.
            preserved_count += 1
            final_status = ex_status
            final_details = _merge_finding_details(ex_details, new_details)
            conflict_note = (
                f"CONFLICT: new scan reports Open — {timestamp_note}"
            )
            final_comments = _merge_comments(
                ex_comments, f"{new_comments_base}\n{conflict_note}"
            )
        # --- Assessor-entered comments: preserve, append stigcode update ---
        elif _is_assessor_comments(ex_comments):
            if ex_status != new_status_str and ex_status not in ("", CklStatus.NOT_REVIEWED.value):
                # Status changed; assessor had explicitly set something different.
                updated_count += 1
            else:
                preserved_count += 1
            final_status = new_status_str
            final_details = _merge_finding_details(ex_details, new_details)
            final_comments = _merge_comments(
                ex_comments, f"{new_comments_base}\n{timestamp_note}"
            )
        # --- Stigcode-generated or empty: replace ---
        else:
            if ex_status != new_status_str:
                updated_count += 1
            else:
                preserved_count += 1
            final_status = new_status_str
            final_details = new_details
            final_comments = (
                f"{new_comments_base}\n{timestamp_note}" if new_comments_base else ""
            )

        _write_vuln(
            istig, finding, stig_ref, final_status,
            final_details, final_comments, ex_sev_override, ex_sev_just,
        )

    tree = ET.ElementTree(root)
    ET.indent(tree, space="\t")
    xml_str = '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding="unicode")
    output_path.write_text(xml_str, encoding="utf-8")

    return UpdateResult(
        updated_count=updated_count,
        preserved_count=preserved_count,
        conflicts=conflicts,
        total_findings=len(benchmark.findings),
    )


# ---------------------------------------------------------------------------
# XML helpers
# ---------------------------------------------------------------------------

def _get_stig_attr(vuln: ET.Element, attr_name: str) -> str:
    """Return the ATTRIBUTE_DATA value for the named VULN_ATTRIBUTE."""
    for sd in vuln.findall("STIG_DATA"):
        if sd.findtext("VULN_ATTRIBUTE") == attr_name:
            return sd.findtext("ATTRIBUTE_DATA") or ""
    return ""


def _write_vuln(
    istig: ET.Element,
    finding,
    stig_ref: str,
    status: str,
    finding_details: str,
    comments: str,
    severity_override: str,
    severity_justification: str,
) -> None:
    """Write a VULN element using provided status/detail/comment values."""

    vuln = ET.SubElement(istig, "VULN")

    attr_values: dict[str, str] = {
        "Vuln_Num": finding.vuln_id,
        "Severity": finding.severity,
        "Group_Title": finding.group_title,
        "Rule_ID": finding.rule_id,
        "Rule_Ver": finding.check_id,
        "Rule_Title": finding.title,
        "Vuln_Discuss": finding.description,
        "IA_Controls": "",
        "Check_Content": finding.check_content,
        "Fix_Text": finding.fix_text,
        "False_Positives": "",
        "False_Negatives": "",
        "Documentable": "false",
        "Mitigations": "",
        "Potential_Impact": "",
        "Third_Party_Tools": "",
        "Mitigation_Control": "",
        "Responsibility": "",
        "Security_Override_Guidance": "",
        "Check_Content_Ref": "M",
        "Weight": "10.0",
        "Class": "Unclass",
        "STIGRef": stig_ref,
        "TargetKey": "",
        "STIG_UUID": "",
    }

    for attr_name in _VULN_ATTRIBUTES:
        _add_stig_data(vuln, attr_name, attr_values.get(attr_name, ""))

    for cci in finding.cci_refs:
        _add_stig_data(vuln, "CCI_REF", cci)

    _sub_text(vuln, "STATUS", status)
    _sub_text(vuln, "FINDING_DETAILS", finding_details)
    _sub_text(vuln, "COMMENTS", comments)
    _sub_text(vuln, "SEVERITY_OVERRIDE", severity_override)
    _sub_text(vuln, "SEVERITY_JUSTIFICATION", severity_justification)
